theme: jekyll-theme-minimal
title: Chelsey Wegener Thesis Homepage
description: This is a place to organize my thesis data anlysis and allow others to view my figures more easily. Thanks for checking this out!
