theme: jekyll-theme-minimal
title: Weclome to Cmwegener's thesis homepage!
description: This is a place to organize my thesis data anlysis and allow others to view my figures more easily. Thanks for checking this out!
